# Floorplan Lovelace
# https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489
#
#      image: /local/custom_ui/floorplan/floorplan.svg
#      stylesheet: /local/custom_ui/floorplan/floorplan.css
#

title: FloorPlan
views:
  - path: floorplan
    title: FloorPlan
    panel: true
    cards:
      - title: Floorplan
        type: 'custom:floorplan-card'
        image: /local/floorplan/hilton/floorplan.svg
        stylesheet: /local/floorplan/hilton/floorplan.css
        rules:
          - entities:
              - light.living_room
              - light.master_bedroom
              - light.office
              - binary_sensor.garage_workbench_light_switch
            states:
              - class: 'light-off'
                state: 'off'
              - class: 'light-on'
                state: 'on'