# Floorplan Lovelace
# https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489
#
#      image: /local/custom_ui/floorplan/floorplan.svg
#      stylesheet: /local/custom_ui/floorplan/floorplan.css
#

title: FloorPlan
views:
  - path: floorplan
    title: FloorPlan
    cards:
      - !include /config/lovelace/tiles/tiles_floorplan.yaml