views:
  - title: Floorplan
    path: floorplan
    panel: true
    cards:
      - type: 'custom:floorplan-card'
        full_height: true
        config:
          image: /local/floorplan/hilton/floorplan.svg
          stylesheet: /local/floorplan/hilton/floorplan.css
          log_level: info
          console_log_level: info
          defaults:
            hover_action: hover-info
            tap_action: more_info
          rules:
            # Rooms
            - entities:
                - binary_sensor.office_illumination
                - binary_sensor.lounge_room_illumination
                - binary_sensor.master_bedroom_illumination
              state_action:
                action: call-service
                service: floorplan.class_set
                  service_data: '${(entity.state === "on") ? "room-light" : "room-dark"}'
              hover_action: false
              tap_action: false
  
            # Lights
            - entities:
                - light.master_bedroom
                - light.lounge
                - light.office
              state_action:
                action: call-service
                service: floorplan.class_set
                  service_data: '${(entity.state === "on") ? "light-on" : "light-off"}'
           
            # Doors
            - entities:
                - binary_sensor.front_door
                - binary_sensor.back_door
                - binary_sensor.garage_door
                - binary_sensor.pantry_door
              state_action:
                action: call-service
                service: floorplan.class_set
                  service_data: '${(entity.state === "on") ? "door-open" : "door-closed"}'
