# Floorplan Lovelace
# https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489
#
#      image: /local/custom_ui/floorplan/floorplan.svg
#      stylesheet: /local/custom_ui/floorplan/floorplan.css
#

title: Floor Plan
views:
  - path: floorplan
    title: Floor Plan
    cards:
      - config:
        image: /local/floorplan/hilton/floorplan.svg
        rules:
          - entities:
              - light.bedroom
              - light.living_room
              - light.master_bedroom
              - light.office
            states:
              - class: 'light-off'
                state: 'off'
              - class: 'light-on'
                state: 'on'
        stylesheet: /local/floorplan/hilton/floorplan.css
        title: Hilton
        type: "custom:floorplan-card"