# Floorplan Lovelace
# https://community.home-assistant.io/t/floorplan-now-available-as-a-lovelace-card/115489
#
#      image: /local/custom_ui/floorplan/floorplan.svg
#      stylesheet: /local/custom_ui/floorplan/floorplan.css
#

title: FloorPlan
views:
  - path: floorplan
    title: FloorPlan
    panel: true
    cards:
      - title: Floorplan
        type: 'custom:floorplan-card'
        image: /local/floorplan/hilton/floorplan.svg
        stylesheet: /local/floorplan/hilton/floorplan.css
        rules:
          # Rooms
          - entities:
              - binary_sensor.office_illumination
              - binary_sensor.lounge_room_illumination
              - binary_sensor.master_bedroom_illumination
              - binary_sensor.garage_workbench_illumination
            states:
              - class: 'room-light'
                state: 'on'
              - class: 'room-dark'
                state: 'off'

          # Lights
          - entities:
              - light.bedroom_light
              - light.lounge_room_light
              - light.office_light
              - switch.garage_workbench_light_relay
            states:
              - class: 'light-off'
                state: 'off'
              - class: 'light-on'
                state: 'on'
          
          # Doors
          - entities:
              - binary_sensor.front_door
              - binary_sensor.back_door
              - binary_sensor.garage_door
              - binary_sensor.pantry_door
            states:
              - class: 'door-closed'
                state: 'off'
              - class: 'door-open'
                state: 'on'
                