dist: bionic
language: python
python:
  - "3.7"
before_install:
  - mv secrets_travis.yaml secrets.yaml
  - mv tensorflow/models/frozen_inference_graph.pb_travis tensorflow/models/frozen_inference_graph.pb
  - sudo apt-get install -y libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev libatlas-base-dev libopenjp2-7 libtiff5
  - sudo ln -s /home/travis/build/Helamorious/HomeAssistant/ /config
  - git clone https://github.com/claytonjn/hass-circadian_lighting.git
  - mv hass-circadian_lighting/custom_components/circadian_lighting /config/custom_components/
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
