dist: bionic
language: python
python:
  - "3.7"
before_install:
  - mv secrets_travis.yaml secrets.yaml
  - mv tensorflow/models/frozen_inference_graph.pb_travis tensorflow/models/frozen_inference_graph.pb
  - sudo apt-get install -y libudev-dev libavformat-dev libavcodec-dev libavdevice-dev libavutil-dev libswscale-dev libswresample-dev libavfilter-dev libatlas-base-dev libopenjp2-7 libtiff5
  - sudo ln -s /home/travis/build/Helamorious/HomeAssistant/ /config
install:
  - pip3 install homeassistant
script:
  - /config/travis_scripts/circadian_lighting.sh
  - hass -c . --script check_config --info all
