# Main Configuration

## Main Settings
# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Hilton
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret tz
  # Authentication Providers
  # https://www.home-assistant.io/docs/authentication/providers/
  auth_providers:
    - type: homeassistant

  # Packages
  # https://home-assistant.io/docs/configuration/packages/ 
  packages: !include_dir_named packages

## Integrations

# API
# https://www.home-assistant.io/components/api/
# https://developers.home-assistant.io/docs/en/external_api_rest.html
# Depends on 'http'
api:

# Automation
# https://www.home-assistant.io/integrations/automation/
automation:

# Config
# https://www.home-assistant.io/components/config/
config:

# Discovery
# https://www.home-assistant.io/integrations/discovery/
discovery:

# FFMPEG
# https://www.home-assistant.io/integrations/ffmpeg/
ffmpeg:

# Frontend
# https://www.home-assistant.io/integrations/frontend/
frontend:

# History
# https://www.home-assistant.io/components/history
history:

# HTTP
http:

# Philips Hue
hue: !include config/hue.yaml

# IOS
# Depends on 'mobile_app', 'discovery'
ios:

# Logbook
# https://www.home-assistant.io/components/logbook/
# Note: All entries need to also be defined in recorder.yaml
logbook: 

# Lovelace UI
# https://www.home-assistant.io/lovelace/
lovelace:
#  mode: yaml

# Map
# https://www.home-assistant.io/integrations/map/
map:

# Mobile App
# https://www.home-assistant.io/integrations/mobile_app/
mobile_app:

# MQTT
mqtt: !include config/mqtt.yaml

# Notify
notify: !include config/discord.yaml

# Person
# https://www.home-assistant.io/integrations/person/
#   Configurations moved into package 'person.yaml' to group users and customizations
person:

# Recorder
# https://www.home-assistant.io/components/recorder/
recorder:

# Script
# https://www.home-assistant.io/integrations/script/
script:

# Simple Service Discovery Protocol
# https://www.home-assistant.io/integrations/ssdp/
ssdp:

# Sun
# https://www.home-assistant.io/integrations/sun/
sun:

# System Health
# https://www.home-assistant.io/integrations/system_health/
system_health:

# TP-Link Kasa
# https://www.home-assistant.io/integrations/tplink/
tplink:

# Ubiquiti Protect

# Updater
# https://www.home-assistant.io/integrations/updater/
updater:

# ZeroConf
# https://www.home-assistant.io/integrations/zeroconf/
zeroconf:
