# InfluxDB https://www.home-assistant.io/integrations/influxdb/

api_version: 2
ssl: false
host: !secret hass_influx_ip
port: 8086
token: !secret hass_influx_token
organization: !secret hass_influx_orgid
bucket: homeassistant
tags:
  source: HA
tags_attributes:
  - friendly_name
include:
  entities:
    - sensor.garage_temperature
    - sensor.kitchen_temperature
    - sensor.master_bedroom_temperature
    - sensor.office_temperature
    - sensor.outside_temperature
    - sensor.garage_humidity
    - sensor.kitchen_humidity
    - sensor.master_bedroom_humidity
    - sensor.office_humidity
    - sensor.outside_humidity
    - sensor.garage_pressure
    - sensor.kitchen_pressure
    - sensor.master_bedroom_pressure
    - sensor.office_pressure
    - sensor.outside_pressure