influxdb:
  api_version: 2
  ssl: true
  verify_ssl: false
  host: hass_influx
  port: 8086
  token: !secret hass_influx_token
  organization: !secret hass_influx_orgid
  bucket: homeassistant
  tags:
    source: HA
  tags_attributes:
    - friendly_name
  default_m,easurement: units
