# Circadian light ( https://community.home-assistant.io/t/circadian-light-with-philips-hue-independent-from-world-clocks/45435 )

sensor:
  - platform: template
    sensors:
      length_of_day_factor:
        friendly_name: 'Circadian Light - Length of Day'
        value_template: >
          {% if is_state('sun.sun' , 'above_horizon') %}
            {% set daylength = ((as_timestamp(states.sun.sun.attributes.next_setting) - as_timestamp(states.sun.sun.attributes.next_rising)) / 3600) + 24 %}
              {{ (daylength*-0.0063616)+0.11131 }}
          {% endif %}
  - platform: template
    sensors:
      farbtemp:
        friendly_name: 'Circadian Light - Colour Temperature'
        unit_of_measurement: 'mired'
        value_template: >
          {% if is_state('sun.sun' , 'above_horizon') %}
            {{ ((states.sensor.length_of_day_factor.state | round (5))*((states.sun.sun.attributes.azimuth)-180)**2 + 175) | int }}
          {% elif (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 or  (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
            350
          {% else %}
            390
          {% endif %}

automation:
  # Regularly update the farbtemp sensor for troubleshooting.
  #  Note; this should be updated everytime one of the other automations is called
  - id: mireds_test
    alias: 'Circadian Light - Value Testing'
    trigger:
      platform: time_pattern
      minutes: '/2'
    action:
      - service: homeassistant.update_entity
        entity_id: sensor.farbtemp

  # Update the colour temperature every 2 minutes
  #  Note; These is set to 2mins to catch any time the lights are activated by the Hue remotes.
  - id: mireds_bedroom
    alias: 'Circadian Light - Bedroom'
    trigger:
      platform: time_pattern
      minutes: '/2'
    condition:
      - condition: state
        entity_id: light.bedroom
        state: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.bedroom
          color_temp: "{{ states.sensor.farbtemp.state }}"

  - id: mireds_lounge1
    alias: 'Circadian Light - Lounge 1 (TV)'
    trigger:
      platform: time_pattern
      minutes: '/2'
    condition:
      - condition: state
        entity_id: light.lounge
        state: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.lounge
          color_temp: "{{ states.sensor.farbtemp.state }}"

  - id: mireds_lounge2
    alias: 'Circadian Light - Lounge 2 (PC)'
    trigger:
      platform: time_pattern
      minutes: '/2'
    condition:
      - condition: state
        entity_id: light.office
        state: 'on'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.office
          color_temp: "{{ states.sensor.farbtemp.state }}"