# Keep the configuration up to date with the latest stable release

# Note; when using travis-ci.com (instead of .org), need to fix the
#  URI thats passed into travispy. This is done at:
#    /usr/src/homeassistant/homeassistant/components/travisci/sensor.py
#  By modifying line 65 to:
#    travis = TravisPy.github_auth(token, uri='https://api.travis-ci.com')

# Connect to TravisCI
sensor:
  - platform: travisci
    api_key: !secret github_access_token
    repository: Helamorious/HomeAssistant

# Create a item to hold the value of the current version
input_text:
  current_build_id:

# The Shell Command to update GIT
shell_command:
  git_pull: 'git pull'

# Create an automation to evaluate if the build is current, and then update if a new build is passing TravisCI
automation:
  id: "config_updater"
  alias: "Configuration Updater"
  trigger:
    platform: template
    value_template: "{{ not(is_state('sensor.helamorious_homeassistant_last_build_id', states('input_text.current_build_id'))) }}"
  condition: "{{ is_state('sensor.helamorious_homeassistant_last_build_state','passed') }}"
  action:
    - service: input_text.set_value
      target:
        entity_id: input_text.current_build_id
      data:
        value: "{{ states('sensor.helamorious_homeassistant_last_build_id') }}"
    - service: shell_command.git_pull
    - service: homeassistant.restart