# Keep the configuration up to date with the latest version in the repository if
# it is passing build checks.

# Note; when using travis-ci.com (instead of .org), need to fix the
#  URI thats passed into travispy. This is done at:
#    /usr/src/homeassistant/homeassistant/components/travisci/sensor.py
#  By modifying line 65 to:
#    travis = TravisPy.github_auth(token, uri='https://api.travis-ci.com')

# Connect to TravisCI
sensor:
  - platform: travisci
    api_key: !secret github_access_token
    repository: Helamorious/HomeAssistant

# Create a item to hold the value of the current version
input_text:
  current_build_id:

# The Shell Command to update GIT
shell_command:
  git_pull: 'git pull'

# Configuration update automation
#  If there is a new build
#  And the build state is passing Travis-CI checks
#  Pull the repo, and restart HA
automation:
  id: "config_updater"
  alias: "Configuration Updater"
  trigger:
    - platform: state
      entity_id: sensor.helamorious_homeassistant_state
      to: "passed"
  action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.current_build_id
        value: "{{ states('sensor.helamorious_homeassistant_last_build_id') }}"
    - service: shell_command.git_pull
    - service: homeassistant.restart