# Keep the configuration up to date with the latest stable release

# Connect to TravisCI
sensor:
  - platform: travisci
    api_key: !secret github_access_token
    repository: Helamorious\HomeAssistant

# Create a item to hold the value of the current version
input_text:
  current_build_id:

# The Shell Command to update GIT
shell_command:
  git_pull: 'git pull'

automation:
  # When the build ID doesn't match our current build
  trigger:
    - platform: template
      value_template: "{{ state_attr('sensor.travisci', 'last_build_id') != state('input_text.current_build_id')}}"
  # If its a successful build
  condition:
    - condition: "{{state_attr('sensor.travisci', 'travisci_last_build_state') == 'passed'}}"
  action:
    # Run these actions in order...
    sequence:
      # Update our value
      - service: input_text.current_build_id
        target:
          entity_id: input_text.current_build_id
        data:
          value: "{{ state_attr('sensor.travisci', 'last_build_id') }}"
      # Fetch the new config from GIT
      - service: shell_command.git_pull
      # Restart HomeAssistant
      - service: homeassistant.restart