# https://www.home-assistant.io/integrations/ring/

# Physical Things
# * Ring Video Doorbell - 'Front Door'

ring:
  username: !secret ring_user
  password: !secret ring_pass

camera:
  - platform: ring
  - platform: local_file
    name: Doorbell_LastVideo
    file_path: '/downloads/Front Door/Front Door'

binary_sensor:
  - platform: ring

sensor:
  - platform: ring

downloader:
  download_dir: downloads

image_processing:
  - platform: tensorflow
    scan_interval: 10000
    source:
      - entity_id: camera.Doorbell_LastVideo
    file_out:
      - "/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      - "/tmp/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      graph: /home/homeassistant/.homeassistant/tensorflow/frozen_inference_graph.pb
      categories:
        - person
        - car
        - truck

automation:
- id: doorbell_press
  alias: 'Doorbell Press'
  initial_state: on
  trigger:
    - entity_id: binary_sensor.ring_front_door_ding
      platform: state
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data_template:
        payload: 'ding'
        topic: 'hilton/front/doorbell/1/status'
    - service: notify.discord
      data:
        target: !secret discord_channel
        message: '[NOTIFY] Ding Dong. Someones at the door.'
    - service: downloader.download_file
      data_template:
        url: "{{ state_attr('camera.front_door', 'video_url') }}"
        subdir: "{{state_attr('camera.front_door', 'friendly_name')}}"
        filename: "{{state_attr('camera.front_door', 'friendly_name')}}"

- id: ring_download_complete
  alias: "Doorbell Video Download Complete"
  initial_state: on
  trigger:
    - platform: event
      event_type: downloader_download_complete
      filename: "Front Door"
  action:
    - service: image_processing.scan
      entity_id: camera.Doorbell_LastVideo
      
- id: ring_download_processed
  alias: "Doorbell Video Person Detected"
  initial_state: on
  trigger:
    platform: event
    event_type: image_processing.detect_face
      entity_id: camera.Doorbell_LastVideo
  action:
    - service: notify.discord
      data:
        target: !secret discord_channel
        message: '[NOTIFY] Person Detected.'
          data:
            images:
              - "/tmp/Front Door_latest.jpg"
