# https://www.home-assistant.io/integrations/ring/

# Physical Things
# * Ring Video Doorbell - 'Front Door'

# Enable the Ring integration
ring:
  username: !secret ring_user
  password: !secret ring_pass

camera:
  # Import Ring camera devices
  - platform: ring
  # Create a camera instance for processing a local file
  - platform: local_file
    name: front_door_lastvideo
    file_path: '/config/tmp/front_door.mp4'
    
binary_sensor:
  # Import Ring binary sensors
  - platform: ring

sensor:
  # Import Ring sensors
  - platform: ring


downloader:
  # Enable the downloader integration
  #  This is used to download cloud video files in the DOORBELL PRESS automation flows
  download_dir: /config/tmp/

image_processing:
  # Create a tensorflow instance for person detection
  #  This is used by the DOORBELL PRESS automation flows
  - platform: tensorflow
    scan_interval: 10000
    # Note; Hopefully source entity_id isn't required so that this can be reused for any automation flow against multiple camera sources
    #source:
    #  - entity_id: camera.front_door_lastvideo
    file_out:
      # Generate a still image and overwrite latest.jpg when a person is detected
      - "/config/tmp/{{ camera_entity.split('.')[1] }}_latest.jpg"
      # Note; in future we may wish to keep a record of all detected people...
      #- "/config/www/{{ camera_entity.split('.')[1] }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
    model:
      # Configure the tensorflow learning data
      graph: /config/tensorflow/frozen_inference_graph.pb
      categories:
        - person

automation:
# DOORBELL PRESS
# This automation flow is intended to allow for facial recognition on the Ring video when the
# doorbell is pressed. This is done in three parts to allow reacting to the completion of the
# downlaod, and completion of the TensorFlow image processing.

# DOORBELL PRESS - Part 1 of 3
# When someone presses the doorbell
#  Send a notification to Discord, and
#  Download the associated video from the Ring cloud service
- id: doorbell_press
  alias: 'Doorbell Press'
  initial_state: on
  trigger:
    - entity_id: binary_sensor.ring_front_door_ding
      platform: state
      from: 'off'
      to: 'on'
  action:
    - service: notify.discord
      data:
        target: !secret discord_channel
        message: '[NOTIFY] Ding Dong. Someones at the door.'
    - service: downloader.download_file
      data_template:
        url: "{{ state_attr('camera.front_door', 'video_url') }}"
        filename: 'front_door.mp4'

# DOORBELL PRESS - Part 2 of 3
# When a Ring video is finished downloading
#  Pass it to the Tensorflow image processor
- id: ring_download_complete
  alias: "Doorbell Video Download Complete"
  initial_state: on
  trigger:
    - platform: event
      event_type: downloader_download_complete
        filename: "front_door.mp4"
  action:
    - service: image_processing.scan
      data:
        entity_id: camera.front_door_lastvideo

# DOORBELL PRESS - Part 3 of 3
# When TensorFlow identifies a person within the video
#  Send a notification to Discord with the image of the detected face attached
- id: ring_download_processed
  alias: "Doorbell Video Person Detected"
  initial_state: on
  trigger:
    platform: event
    event_type: image_processing.detect_face
      entity_id: camera.front_door_lastvideo
  action:
    - service: notify.discord
      data:
        target: !secret discord_channel
        message: '[NOTIFY] Person Detected.'
          data:
            images:
              - "/config/tmp/front_door_lastvideo_latest.jpg"
