# https://www.home-assistant.io/integrations/ring/

# Physical Things
# * Ring Video Doorbell - 'Front Door'

ring:
  username: !secret ring_user
  password: !secret ring_pass

camera:
  - platform: ring
  - platform: local_file
    name: Doorbell
    file_path: '/downloads/Front Door/Front Door'

binary_sensor:
  - platform: ring

sensor:
  - platform: ring

downloader:
  download_dir: downloads

automation:
- id: doorbell_press
  alias: 'Doorbell Press'
  initial_state: on
  trigger:
    - entity_id: binary_sensor.ring_front_door_ding
      platform: state
      from: 'off'
      to: 'on'
  action:
    - service: mqtt.publish
      data_template:
        payload: 'ding'
        topic: 'hilton/front/doorbell/1/status'
    - service: notify.discord
      data:
        target: !secret discord_channel
        message: '[NOTIFY] Ding Dong. Someones at the door.'
    - service: downloader.download_file
      data_template:
        url: "{{ state_attr('camera.front_door', 'video_url') }}"
        subdir: "{{state_attr('camera.front_door', 'friendly_name')}}"
        filename: "{{state_attr('camera.front_door', 'friendly_name')}}"
    - delay: 0:30
    - service: image_processing.scan
      data:
        source: /downloads/Front Door