# This is to add room objects that FloorPlan can use to manipulate room illumination rendering based on light status

binary_sensor:
  - platform: template
    sensors:
      office_illumination:
        friendly_name: "Office Illumination"
        value_template: "{{ is_state('light.office', 'on') }}"

      lounge_room_illumination:
        friendly_name: "Lounge Room Illumination"
        value_template: "{{ is_state('light.lounge', 'on') }}"

      master_bedroom_illumination:
        friendly_name: "Master Bedroom Illumination"
        value_template: "{{ is_state('light.master_bedroom', 'on') }}"

      garage_workbench_illumination:
        friendly_name: "Garage Workbench Illumination"
        value_template: "{{ is_state('switch.garage_workbench_light', 'on') }}"