# https://developers.home-assistant.io/blog/2020/04/16/hassfest/

name: Hassfest

on:
  push:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout
        uses: "actions/checkout@master"
      - name: check config
        uses: "glitchcrab/action-hass-check-config@main"